version: '3' # docker-compose 버전 지정
services:  # docker-compose의 경우 docker 컨테이너로 수행될 서비스들은 services 하위에 기술
    composeTestSpring1: # 서비스 이름. service 하위에 작성하면 해당 이름으로 동작
        image: ojjinseok/compose1:latest # 도커 이미지
        build: ./composeTest1
        ports: # 외부포트:컨테이너내부포트
            - "8081:8081"
    composeTestSpring2:
        image: ojjinseok/compose2:latest
        build: ./composeTest2
        ports: # 외부포트:컨테이너내부포트
            - "8082:8082"
    composeTestReact:
        image: ojjinseok/compose3:latest
        build: ./compose-test-3
        ports: # 외부포트:컨테이너내부포트
            - "3000:3000"